
# SEO settings
title: "hp"
title2: "techguy" # default: ""
description: "(senior) software engineer - web developer - full stack developer - team leader - security researcher."
keywords: "hptechguy, techguy, js, javascript, web, security, researcher, jquery, .net, .net framework, angularjs, reactjs, data and algorithm, computer science, full stack, front-end, back-end, information technology, database, ly hong phat, hong phat ly, phat ly."
url: http://heiswayi.github.io/thinkspace # site url
#baseurl: "/hptechguy.github.io" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-89360024-1
repo: http://github.com/heiswayi/thinkspace
disqus_shortname: "hptechguy"
twitter_username: "_hptechguy"
comments: true 

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Hong Phat Ly"
  job      : "(Senior) Software Engineer, Web Developer, Full Stack Developer, Team Leader, Security Researcher"
  bio      : "I have ever worked on a lot of various projects and applications at Viettel Corporation and TMA Solutions. Additionally, I developed some of personal projects and found some security bugs for United Airlines, Nahi JSC, Namecheap, etc..."
  thumb    : /images/author.jpg
  email    : phat.ly.27@gmail.com
  url      : http://hptechguy.github.io
  github   : http://github.com/hptechguy
  twitter  : http://twitter.com/_hptechguy
  facebook : https://www.facebook.com/profile.php?id=1257583160
  linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@_hptechguy"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
